import type { Metadata } from "next";
import "./globals.css";
import React from 'react';
import Head from 'next/head';
import Navbar from '@/Components/Navbar';
import Footer from '@/Components/Footer';
import ErrorBoundary from '@/Components/ErrorBoundary';

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

